### ISSUE TITLE
Add code coverage GitHub integration

### ISSUE THREAD

**Issue by IanLee1521** [dhs-ncats/pshtt#117]
https://coveralls.io

Related to my work in: https://github.com/ianlee1521/pshtt/tree/test-framework

**Comment by IanLee1521** [comment]
Hmm. Or maybe codecov.io would be better?

https://www.slant.co/improve/versus/7928/7929/~coveralls_vs_codecov

**Comment by IanLee1521** [comment]
Example in that fork where I just got this to track the results: https://coveralls.io/github/IanLee1521/pshtt

**Comment by IanLee1521** [comment]
Defer to @h-m-f-t, as enabling this requires repository admin rights.

**Comment by h-m-f-t** [comment]
Resolved with #119.
