### ISSUE TITLE
Hanging on domains whose page load can never complete

### ISSUE THREAD

**Issue by jsf9k** [dhs-ncats/pshtt#138]
`pshtt` hangs on domains like [lrostk.gsfc.nasa.gov](https://lrostk.gsfc.nasa.gov) and [gs-444-lrostk.gsfc.nasa.gov](https://gs-444-lrostk.gsfc.nasa.gov) where it can connect and bytes keep coming, but the page will never complete loading.  These particular pages load a single image of MIME type `multipart/x-mixed-replace`, which is a stream that never completes.

**Comment by jsf9k** [comment]
This can probably be fixed by making use of [streaming requests](http://docs.python-requests.org/en/master/user/advanced/#streaming-requests) inside the `ping` method of `pshtt.py`.  I will create a pull request for this issue.

**Comment by konklone** [comment]
Fixed by #140.
