### ISSUE TITLE
Confirming SPF for Guideline.gov

### ISSUE THREAD

**Issue by erm161** [dhs-ncats/pshtt#151]
I am writing to inquire why SPF is not being recognized for guideline.gov. Thank you for your time.

**Comment by h-m-f-t** [comment]
Hi @erm161. pshtt doesn't scan for SPF or email-related records, but our [trustymail](https://github.com/dhs-ncats/trustymail/) tool does.

There was a recent discussion in the trustymail issues about your domain, so do check out https://github.com/dhs-ncats/trustymail/issues/39.
