### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by trevorbryant** [dhs-ncats/pshtt#190]
Is Python 2 still required? Installing from `pip` errors with `Could not find a version that satisfies the requirement sslyze>=2.0.6`.

The install instructions state Python3  is supposed. Should the instructions be updated for `pip3` installs?

**Comment by jsf9k** [comment]
Hi @trevorbryant!

The instructions assume that your local, default python is version 3.  If your local default python is version 2 then yes, you should install via `pip3` and run with `python3`.

I'm going to close this issue, but feel free to reopen if you disagree.

**Comment by trevorbryant** [comment]
Thanks for the response! I think I'll send a PR as that lack of instructional detail will eventually come back.
