### ISSUE TITLE
sslyze module error when attempting to run pshtt

### ISSUE THREAD

**Issue by TejKanitkar** [dhs-ncats/pshtt#210]
![use this scrennshot](https://user-images.githubusercontent.com/13122925/84310608-ea3e8580-ab2f-11ea-9420-7cbb1d4753a0.jpg)

python3 --version is 3.7, sslyze --version is 3.0.6

did I install pshtt or sslyze incorrectly? Tried updating sslyze, tried manually installing pshtt, nothing's working

**Comment by mcdonnnj** [comment]
This was band-aided in https://github.com/cisagov/pshtt/pull/211, and will fixed when #209 is resolved.
