### ISSUE TITLE
Can't install latest version on python 3.8

### ISSUE THREAD

**Issue by epicfaace** [dhs-ncats/pshtt#213]
When I install the latest version on python 3.8, I get an error:

```
$ pip install pshtt==0.6.7
...
ERROR: Could not find a version that satisfies the requirement nassl<2.3.0,>=2.2.0 (from sslyze<3.0.0,>=2.1.3->pshtt==0.6.7) (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3, 3.0.0)
ERROR: No matching distribution found for nassl<2.3.0,>=2.2.0 (from sslyze<3.0.0,>=2.1.3->pshtt==0.6.7)
```

However, the older version works fine:
```
$ pip install pshtt==0.6.6
...
Successfully installed DataProperty-0.50.0 beautifulsoup4-4.9.1 certifi-2020.6.20 cffi-1.14.2 chardet-3.0.4 cryptography-2.9 docopt-0.6.2 idna-2.10 jsonschema-3.2.0 mbstrdecoder-1.0.0 msgfy-0.1.0 nassl-3.0.0 path-15.0.0 path.py-12.5.0 pathvalidate-2.3.0 pshtt-0.6.6 publicsuffix-1.1.1 pycparser-2.20 pyopenssl-19.1.0 pyrsistent-0.16.0 pytablereader-0.30.1 pytablewriter-0.58.0 python-dateutil-2.8.1 pytz-2020.1 requests-2.24.0 soupsieve-2.0.1 sslyze-3.0.8 tabledata-1.1.3 tcolorpy-0.0.8 tls-parser-1.2.2 typepy-1.1.1 urllib3-1.25.10 wget-3.2
```

Must have been caused by #211 (@cablej ?)

**Comment by mcdonnnj** [comment]
@epicfaace thank you for your interest in our projects. Unfortunately this is a result of the builds for [nassl](https://github.com/nabla-c0d3/nassl). There are no Python 3.8 wheels (`bdist`) for the following versions: `1.1.0`, `1.1.2`, `1.1.3`, `2.00`, `2.1.0`, `2.1.1`, `2.1.2`, and `2.2.0`. There is also no source (`sdist`) option to fall back on after version `1.0.3`. The result of this is that Python 3.8 is unsupported by [nassl](https://github.com/nabla-c0d3/nassl) wheels until version `3.0.0`, and we cannot support `3.0.0` until a significant rewrite is undertaken to account for the changes in that version. The only workaround for Python 3.8 is to download the [source for `2.2.0`](https://github.com/nabla-c0d3/nassl/releases/tag/2.2.0) and manually install the package.
