### ISSUE TITLE
Change the library used to access the public suffix list since the `publicsuffix` package is deprecated

### ISSUE THREAD

**Issue by BastianZim** [dhs-ncats/pshtt#217]
# 💡 Summary #

publicsuffix, a dependency of this project, is outdated and will not be supported anymore: https://pypi.org/project/publicsuffix/

## Motivation and context ##

This makes it difficult to install it in different environments where publicsuffix is not available as it will never be ported, furthermore, it might introduce security risks and outdated information.

## Implementation notes ##

An alternative is the mentioned packages:

- https://pypi.org/project/publicsuffixlist/
- https://pypi.org/project/publicsuffix2/

or downloading the list directly: 

- https://publicsuffix.org/list/ (Asks to not be downloaded more than once per day)
- https://github.com/publicsuffix/list

## Acceptance criteria ##

How do we know when this work is done?

- [ ] publicsuffix is removed from the codebase

**Comment by michaelblyons** [comment]
See #237?

**Comment by mcdonnnj** [comment]
> See #237?

Good catch. This never got linked appropriately.
