### ISSUE TITLE
Unable to install with PIP

### ISSUE THREAD

**Issue by infopowerbroker** [dhs-ncats/pshtt#218]
# 🐛 Summary #

Unable to use PIP to do a clean pshtt install on a new machine. First you receive a warning about dependencies, then an error for recursive evaluation going too deep.

I was able to get this to work in 2018 and 2019, but not in 2021 (installing on a new machine). If I had to guess, I'm thinking the requirements.txt needs to be updated with tighter version constraints. 

for my VM, it runs for 24 hours then ends up with this error (full error in the screenshot below)
Error: pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000

## To reproduce ##

1. Create a new VM with windows subsystem for linux, install python3 + PIP from the bash shell
2. run command  pip install pshtt
3.  wait for it to time out / error (may take 24 hours depending on how fast dependencies evaluate)

## Error logs from Console##

INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. 

ERROR: Exception:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/home/user/.local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/home/user/.local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 316, in run
    requirement_set = resolver.resolve(
  File "/home/user/.local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/home/user/.local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/user/.local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 364, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000

Add any screenshots of the problem here.
![image](https://user-images.githubusercontent.com/14957446/112637892-05efef80-8e15-11eb-83b0-7889704416b1.png)

**Comment by NeckBeardPrince** [comment]
Same issue here. Crazy CISA hasn't acknowledged this.

**Comment by erowley2501** [comment]
I am seeing the same error when attempting to install using the PIP included in the official Python for Windows on Windows 10 and Windows Server 2016.

On Ubuntu 20.04 LTS, I am seeing this error with it's pip 20.0.2 package:
`ERROR: Could not find a version that satisfies the requirement nassl<2.3.0,>=2.2.0 (from sslyze<3.0.0,>=2.1.3->pshtt) (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3, 3.0.0, 3.1.0, 4.0.0)
ERROR: No matching distribution found for nassl<2.3.0,>=2.2.0 (from sslyze<3.0.0,>=2.1.3->pshtt)`

**Comment by SebieF** [comment]
Same issue here (Ubuntu 20.04), I tried with `python3 setup.py install`, seems like sslyze needs `cryptography==2.5`, but installing it manually results in this conflict: `pyopenssl 20.0.1 requires cryptography>=3.2, but you have cryptography 2.5 which is incompatible.`

Edit: Seems like #214 tries to fix this, and installing from the fork from branch sslyze3-support works fine for me :)

**Comment by mcdonnnj** [comment]
This package currently only supports Python 3.6 and 3.7. The current configuration does not *enforce* that limitation, but it is a problem on installation because there are dependency versions that do not support >py3.7.

**Comment by NeckBeardPrince** [comment]
> This package currently only supports Python 3.6 and 3.7. The current configuration does not _enforce_ that limitation, but it is a problem on installation because there are dependency versions that do not support >py3.7.

Instead of just closing the issue could a PR be created to resolve the problem?
