### ISSUE TITLE
Manual Pshtt Scanner Broken

### ISSUE THREAD

**Issue by KeithBonesJr** [dhs-ncats/pshtt#233]
# 🐛 Summary #

Unable to execute a manual pshtt scan for domains. Issue is fixed here #232 . Will need new docker image made available.

## To reproduce ##

1. Execute docker run --volume $PWD/results:/home/scanner/results dhsncats/domain-scan:latest --scan=pshtt ftc.gov

## Expected behavior ##

What did you expect to happen that didn't?

Generate a file with pshtt results for domain

## Any helpful log output or screenshots ##

Paste the results here:

```
MAC-0014539:~ bonesk$  docker run --volume $PWD/results:/home/scanner/results dhsncats/domain-scan:latest --scan=pshtt ftc.gov
[pshtt] Downloading third party data...
Traceback (most recent call last):
  File "./scan", line 622, in <module>
    run(options, unknown, cache_dir, results_dir)
  File "./scan", line 122, in run
    scan_domains(scans, domains, options)
  File "./scan", line 171, in scan_domains
    init = scanner.init(environment, options)  # type: ignore
  File "/home/scanner/scanners/pshtt.py", line 41, in init
    'preload_list': pshtt.load_preload_list(),
  File "/opt/pyenv/versions/3.6.4/lib/python3.6/site-packages/pshtt/pshtt.py", line 1485, in load_preload_list
    raw = base64.b64decode(raw).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 1: invalid continuation byte
MAC-0014539:~ bonesk$

```

Add any screenshots of the problem here.

**Comment by jsf9k** [comment]
I believe this is fixed now with these three commits to [cisagov/domain-scan](https://github.com/cisagov/domain-scan):
- cisagov/domain-scan@2cdac865ec6ccd48924e94a980e73a5e82c3bcee
- cisagov/domain-scan@f2f4cf1f121bcd256719f84f7b444df7e848b948
- cisagov/domain-scan@264188ea62487b7e8606e7cb5368ee101f1dfc87

I built a new `dhsncats/domain-scan:latest` Docker image and pushed it to Docker Hub, so if you pull it and re-run the command @KeithBonesJr listed above it should now work.

@KeithBonesJr and @climber-girl - The `dhsncats` Docker Hub organization is now deprecated in favor of `cisagov`.  I also pushed the new Docker image to `cisagov/domain-scan:latest`, and that is where you should be pulling it from going forward.  Can you please let the others know, update your runbooks accordingly, etc.?
