### ISSUE TITLE
Add support for Python 3.8

### ISSUE THREAD

**Issue by lebeno** [dhs-ncats/pshtt#236]
As explained in issue #213, support for Python 3.8 needs [nassl](https://github.com/nabla-c0d3/nassl) 3.0.0, but pshtt needs a significant rewrite to account for the changes in that version.

Python 3.7 goes end-of-support on 2023-06-27. Is a rewrite planned?

**Comment by lebeno** [comment]
Looks like PR #214 adds support for sslyze>=3.0.0 but is waiting for merge.

**Comment by gbinal** [comment]
Just to +100 this issue, this is holding my team up pretty badly over at GSA.

**Comment by jsf9k** [comment]
Resolved by #248 (a superset of #214).
