### ISSUE TITLE
Rename pshtt_cli to pshtt

### ISSUE THREAD

**Issue by konklone** [dhs-ncats/pshtt#24]
The tool should just use its own name as its CLI executable. This shouldn't interfere with the main file being `pshtt.py` (though that should probably be moved, along with `models.py`, into a `lib/` directory).

**Comment by garrettr** [comment]
As part of my work for #23, I've refactored all of the Python code into a module. Here's what the directory tree looks like now:

```
(env) pshtt ~> tree -I "env|*.pyc|*.csv"
.
├── Dockerfile
├── LICENSE.md
├── README.md
├── entrypoint.sh
├── pshtt
│   ├── __init__.py
│   ├── cli.py
│   ├── models.py
│   ├── pshtt.py
│   └── utils.py
├── requirements.txt
└── setup.py

1 directory, 11 files
```

`pshtt_cli` has been renamed to `pshtt/cli.py`, and can be executed via either `./pshtt/cli.py` or (better, imho) `python -m pshtt.cli`.

Is this an acceptable change? Seems to me it accomplishes the spirit of this issue, although the approach is different.

In addition, it would be very easy to add `pshtt/__main__.py`, which would enable running the module directly, in the manner of the json/timeit/pdb from the standard library: `python -m pshtt <args...>`.

**Comment by konklone** [comment]
This seems acceptable to me. I don't suppose you tried running the Dockerfile to make sure that still all works well? I saw you updated `entrypoint.sh`, which is helpful.
