### ISSUE TITLE
Shift URL for transport_security_state_static.json for new location

### ISSUE THREAD

**Issue by mbachtell-nais** [dhs-ncats/pshtt#240]
# 🐛 Summary #

The URL for transport_security_state_static.json is currently https://chromium.googlesource.com/chromium/src/net/+/master/http/transport_security_state_static.json?format=TEXT but should be https://chromium.googlesource.com/chromium/src/+/main/net/http/transport_security_state_static.json?format=TEXT. 

## Expected behavior ##

The HSTS would preload and pshtt would work (assuming that you are using PR #228 for current versions of Python).

**Error**
![image](https://user-images.githubusercontent.com/126006749/236811500-63cfc106-069d-4fea-afc3-faf721253566.png)

**Working after URL correction**
![image](https://user-images.githubusercontent.com/126006749/236811358-fe103f5a-bb94-41a9-86e9-a221a94cceb0.png)

**Comment by jsf9k** [comment]
I believe this was fixed in #232.  Or am I missing something?

**Comment by mbachtell-nais** [comment]
Ah, you are correct.  I'm working off of PR #214 which has the old URL.  

I will close.
