### ISSUE TITLE
Move some policy decisions into pshtt

### ISSUE THREAD

**Issue by konklone** [dhs-ncats/pshtt#29]
Right now, pulse.cio.gov makes some additional policy decisions on top of `pshtt` data to prepare its published values:
- Uses HTTPS: https://github.com/18F/pulse/blob/master/data/processing.py#L367-L381
- Enforces HTTPS: https://github.com/18F/pulse/blob/master/data/processing.py#L387-L420
- HSTS: https://github.com/18F/pulse/blob/master/data/processing.py#L431-L447
- Preloaded: https://github.com/18F/pulse/blob/master/data/processing.py#L451-L458

This logic should be moved down into `pshtt` so that others don't have to port the above logic to their own demesnes. And users who want to make different policy decisions will still have the direct measurements already in `pshtt` to do that with.

**Comment by h-m-f-t** [comment]
@konklone: I'm sure there's a more sophisticated way to implement this than [this](https://github.com/dhs-ncats/pshtt/blob/fifteen-thirteenize/pshtt/pshtt.py#L105-L135) and would appreciate your take.

- `== False` is more readable than `!= True`, but e.g., `result['Valid HTTPS']` or `result['Downgrades HTTPS']` returns `None` for some domains that should otherwise be False, and it's not clear to me why or under what circumstances this occurs. (FWIW, I've been testing of late with a set of HHS domains with assorted compliance postures: cancer.gov, cdc.gov, clinicaltrials.gov, cms.gov, nlm.gov, psc.gov, surgeongeneral.gov.)
- It makes sense to me to have these fields not be on by default, only included by a `-m` or `--m1513` option. 
- Related to the first bullet, note the [failing build](https://travis-ci.org/dhs-ncats/pshtt/builds/176529046).

**Comment by konklone** [comment]
> == False is more readable than != True, but e.g., result['Valid HTTPS'] or result['Downgrades HTTPS'] returns None for some domains that should otherwise be False, and it's not clear to me why or under what circumstances this occurs.

You should be more explicit with parentheses to ensure you get a predictable order of operations. Right now it's:

```
(
            is_downgrades_https(domain) != True and
            is_bad_chain(domain) and
            is_bad_hostname(domain) != True
)
```

And I think you should make it:

```
(
            (is_downgrades_https(domain) != True) and
            is_bad_chain(domain) and
            (is_bad_hostname(domain) != True)
)
```

Otherwise, it's possible it could be interpreting the statement as if you had parens placed like `is_downgrades_https(domain) != (True and ... )` instead. 

There are a few other locations where explicit parens would be helpful in the code you highlighted.

Also, keep in mind when structuring these how Python logical evaluation and short-circuiting works. From `ipython` (the third statement is evaluating to `None`, which prints nothing):

```
In [1]: True or None
Out[1]: True

In [2]: None or True
Out[2]: True

In [3]: False or None

In [4]: None or False
Out[4]: False
```

> It makes sense to me to have these fields not be on by default, only included by a -m or --m1513 option.

I don't know. I think they are useful high-level conclusions no matter what, but regardless, I actually wouldn't label them specifically as M-15-13. Besides being a bit inscrutable to non-government users who might benefit from their utility, the definitions also involve a looser interpretation than reading M-15-13 literally. Reading M-15-13 literally, you could easily argue it requires `Strictly Forces HTTPS` (immediate redirect to `https://`) to be true (and this is why I created the field originall), but [Pulse](https://pulse.cio.gov) chooses to allow endpoints to _eventually_ redirect, out of an acknowledgment of practical reality and where it's worth focusing enforcement effort.

I would remove the `(M-15-13)` suffix, and name them something useful and rhetorically distinct from the other fields. I don't think they have to be named exactly the same as in Pulse and NCATS reports. Perhaps:

* `Uses HTTPS` -> `Domain Supports HTTPS`. The field is trying to express whether the site is effectively usable over HTTPS and whether the site owner seems to be attempting to support it. A bad hostname makes it clear they are not, whereas an incomplete chain is just a mistake. (Use of non-publicly-trusted certs also generally indicates an attempt to support HTTPS, even if they're making a poor business choice.)
* `Enforces HTTPS` -> `Domain Enforces HTTPS`. The field is trying to express whether the site owner is effectively and intentionally enforcing HTTPS for the domain. For websites, eventually redirecting the user to HTTPS and observing that the site's "canonical" URL is HTTPS is strong enough. For "redirect domains" (uncommon outside the government), redirect behavior and direct support for HTTPS are the only things the domain owner can do, so they should do both of them.
* `HSTS` -> `Domain Uses Strong HSTS`. The field is trying to express that the domain has not just done HSTs, but done it *well*: it's applied HSTS to the URL that the site is typically accessed at (not on the wrong endpoint), and that its max-age is acceptable. I have no issue with the tool generally saying that 1 year constitutes "strong", whether or not M-15-13 specified it.

Also, this definition...

```python
'HSTS (M-15-13)': hsts_max_age(domain) >= 31536000
```

...relies on `hsts_max_age(domain)` always being a number, even if the domain doesn't have HSTS, and is relying on an implicit assurance that an HSTS header with a max-age of > 1 year will never be invalid in some other way. I think that's too much implicitness, and the definition should check that `is_hsts(domain)` is `True` as well.

**Comment by h-m-f-t** [comment]
Onwards and upwards. 🇺🇸
