### ISSUE TITLE
"Downgrades HTTPS" is null for abcnews.go.com

### ISSUE THREAD

**Issue by garrettr** [dhs-ncats/pshtt#49]
When you access `https://abcnews.go.com` in a browser, it downgrades the connection to HTTP; however, it does not use an HTTP redirect:

```
$ curl -I https://abcnews.go.com
HTTP/1.1 200 OK
[..snip..]
```

Instead, it uses Javascript to redirect:

```html
<script>
        if (window.location.protocol == "https:" && window.parent.location.hostname.indexOf("outbrain") == -1) {
                var _sslurl = window.location.href.replace("https://", "http://");
                window.location.replace(_sslurl);
                window.location.href = _sslurl;
        }
</script>
```

pshtt's results are confusing. `pshtt --json abcnews.go.com` returns `"Valid HTTPS": true` but also returns `"Downgrades HTTPS": null`. I would expect that if `"Valid HTTPS" true`, then `"Downgrades HTTPS"` should be one of true or false, but not null. null only makes sense if the site doesn't have valid HTTPS, because then the question of whether or not it downgrades it is moot.

What do y'all think? Is this a bug?

Note that I am *not* saying that pshtt should (necessarily) detect downgrades done with Javascript. While it would be possible (and possibly cool) to implement that, you would need to implement browser automation to do it right, which is a significant expansion of the crawler's current design. However, I do think there seems to be a bug in this case, where the result should be true or false (not null).

**Comment by garrettr** [comment]
This is also the case for theintercept.com, where the value for `"Downgrades HTTPS"` should definitely be `false`.

```
[
  {
    "Base Domain": "theintercept.com", 
    "Canonical URL": "https://theintercept.com", 
    "Defaults to HTTPS": true, 
    "Domain": "theintercept.com", 
    "Domain Enforces HTTPS": true, 
    "Domain Supports HTTPS": true, 
    "Domain Uses Strong HSTS": false, 
    "Downgrades HTTPS": null, 
    "HSTS": true, 
    "HSTS Entire Domain": true, 
    "HSTS Header": "max-age=15768000; includeSubDomains; preload", 
    "HSTS Max Age": 15768000, 
    "HSTS Preload Pending": false, 
    "HSTS Preload Ready": true, 
    "HSTS Preloaded": true, 
    "HTTPS Bad Chain": null, 
    "HTTPS Bad Hostname": null, 
    "HTTPS Expired Cert": null, 
    "Live": true, 
    "Redirect": false, 
    "Redirect To": null, 
    "Strictly Forces HTTPS": true, 
    "Valid HTTPS": true,
[..snip..]
```

**Comment by garrettr** [comment]
The issue appears to be in `is_downgrades_https`, specifically:

```py
    return (
        supports_https and
        canonical_https.redirect_immediately_to_http and
        (not canonical_https.redirect_immediately_to_external)
    )
```

In the case of theintercept.com, ` canonical_https.redirect_immediately_to_http` is None, so this statement is equivalent to `return True and None and something_else`, but thanks to Python's short-circuit evaluation it just returns `None`, which is the source of the `null` in the JSON output.

**Comment by konklone** [comment]
This is a great catch, thank you. I think we didn't notice this on our end because we're using the CSV output, which [papers over this issue](https://github.com/dhs-ncats/pshtt/blob/master/pshtt/pshtt.py#L837-L842).

I believe that the tool should always end up on `true` and `false` answers for every field, and never `null`, so that downstream tools never need to disambiguate a `null` response from a `false` response.
