### ISSUE TITLE
Turn on Travis CI builds for this repository

### ISSUE THREAD

**Issue by konklone** [dhs-ncats/pshtt#5]
There's already a [`.travis.yml`](https://github.com/dhs-ncats/pshtt/blob/master/.travis.yml) that will instruct Travis to run `flake8` on the `.py` files in the repository. It's not exactly unit tests, and it doesn't run `flake8` on `pshtt_cli`, but it's better than nothing.

**Comment by h-m-f-t** [comment]
^^ done.
