### ISSUE TITLE
Error with internal network, self-signed CA

### ISSUE THREAD

**Issue by klauern** [dhs-ncats/pshtt#51]
Does this tool only work with publicly facing websites, or should it be able to work within internal networks with a self-signed cert?  I am not able to run it inside my corporate network, with the following error:

```sh
10:43 $ pshtt server.internal-place.com --json
Traceback (most recent call last):
  File "/usr/bin/pshtt", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/pshtt/cli.py", line 54, in main
    results = pshtt.inspect_domains(domains, options)
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 870, in inspect_domains
    preload_list = create_preload_list()
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 798, in create_preload_list
    request = requests.get(file_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
```

**Comment by konklone** [comment]
@klauern I think the intent here is to have the tool work with whatever the user's constraints are. You should be able to use it with local CAs. If the goal is to have it work with _any_ self-signed certificate, then I don't think that needs any logic changes, but you would ignore all "chain" errors when looking at the tool's output.

It looks like there are two issues here:

* No defined or documented way to specify a modified or additional local trust store. @klauern In your case, is it a specific local CA you want to trust, or do you not care about validating the chain at all? (The latter isn't recommended, but I don't want to make it impossible.)
* A chain error is potentially being handled non-gracefully. @klauern Did you give the full paste details? It's important to identify whether the tool is halting on the stack trace, or whether it's printing out the stack trace for debugging/information purposes but still continuing execution.

**Comment by klauern** [comment]
@konklone 

> is it a specific local CA you want to trust, or do you not care about validating the chain at all? 

It's a corporate proxy, with it's own internal Root/Intermediate CA's.  On my *nix servers, I"ve been able to add these to my trusted CA's and that's generally enough to get things working.  I actually would like to be able to tell whether some of our internal services are using self-signed certs, a different intermediate CA, etc., so I can do some better troubleshooting on our own network.

> Did you give the full paste details? 

Yes, that's all I got from it.  I replaced my internal server name with the `server.internal-place.com`, but everything else is the same.

**Comment by konklone** [comment]
> On my *nix servers, I"ve been able to add these to my trusted CA's and that's generally enough to get things working.

I believe that `pshtt` is pulling its list of trusted CAs from the OS trust store -- so I would expect that adding your corporate CA to the server trust store should resolve this. Have you installed the corporate CA on your scanning vantage point?

**Comment by klauern** [comment]
Yes, the server/host that's running `pshtt` has these CA's installed.  I'm running a variant of Arch Linux, if that's helpful.  I know that the location of the trusts is different for Linux variants, but I don't know how this tool is implementing certificate validation.

**Comment by konklone** [comment]
We're using `requests`, and it looks like it bundles its own trust store based on Mozilla's:

http://docs.python-requests.org/en/master/user/advanced/#ca-certificates

It's not well documented, but [this seems to suggest](https://github.com/kennethreitz/requests/issues/3215#issuecomment-221092279) you can use a `REQUESTS_CA_BUNDLE` environment variable to override the path `requests` uses to point to a CA bundle.

There is an [open issue about moving to the system trust store by default](https://github.com/kennethreitz/requests/issues/2966), but if the environment variable approach works, that could resolve this and we could document it.

@klauern Want to give the env var approach a try?

**Comment by klauern** [comment]
That actually works!

**Comment by klauern** [comment]
Here's some output:

```sh
09:02 $ pshtt internal-server.somewhere.com --json
Failed to connect.
Failed to connect.
Failed to connect.
Failed to connect.
[
  {
    "Base Domain": "somewhere.com",
    "Canonical URL": "http://internal-server.somewhere.com",
    "Defaults to HTTPS": false,
    "Domain": "internal-server.somewhere.com",
    "Domain Enforces HTTPS": null,
    "Domain Supports HTTPS": null,
    "Domain Uses Strong HSTS": false,
    "Downgrades HTTPS": false,
    "HSTS": false,
    "HSTS Entire Domain": null,
    "HSTS Header": null,
    "HSTS Max Age": null,
    "HSTS Preload Pending": false,
    "HSTS Preload Ready": false,
    "HSTS Preloaded": false,
... more stuff
```

**Comment by konklone** [comment]
All right, since it worked, then I think documenting that in the README (and perhaps mentioning it in a code comment) is the right approach. @h-m-f-t Any thoughts?

**Comment by h-m-f-t** [comment]
@konklone, definitely agree. @klauern, would you be willing to take a swing at adding a few details to the README? (Thanks for bringing this up 👍 )

**Comment by klauern** [comment]
Sure thing!
