### ISSUE TITLE
slate.com is a lie

### ISSUE THREAD

**Issue by garrettr** [dhs-ncats/pshtt#53]
At first glance, slate.com appears to be available over HTTPS:

```
$ curl -I https://slate.com | head -n 1
HTTP/1.1 200 OK
```

pshtt agrees, and as a result so does [Secure the News](https://securethe.news/sites/slate-magazine). Unfortunately, upon closer inspection, Slate's secure homepage is a lie:

![screenshot_2017-02-07_00-12-28](https://cloud.githubusercontent.com/assets/407302/22683280/1c61bd78-eccc-11e6-8342-5fe34cdd2a7e.png)

I'm filing this issue simply to bring it to everyone's attention, and potentially start a discussion about what we might do to fix it. Ultimately, I don't think there are any easy answers here: it's hard to automate "this site looks the way it should: y/n". It may simply be the case that projects that use pshtt, like Secure the News, which I hoped would be fully automated and self-updating, will still require a degree of manual intervention to correct for false positive such as this one.

Other ideas or feedback greatly appreciated!

**Comment by konklone** [comment]
Yeah, this has come up internally before, and it's an interesting judgment call. It's been rare enough that I've been willing to basically give this a `Yes` for "Uses HTTPS", because I know that the situation can only be there while "Enforces HTTPS" and "HSTS" are at `No`. In other words, as they progress in their migration, the problem is guaranteed to fix itself.

**Comment by garrettr** [comment]
@konklone That's a good point! At least they can only get up to a C on Secure the News. Feel free to close this issue if you don't think it warrants any development work; I just wanted to make sure it was known and to create a place for discussion in case anybody had any bright ideas!

**Comment by h-m-f-t** [comment]
Thanks @garrettr. I agree this ultimately comes out in the wash, but does mean you've got to check for 'lies' in the data. There are many (many) USG "sites" that are available over HTTPS, though without content-- a default install of IIS or something.
