### ISSUE TITLE
Incorrect "Valid HTTPS" results for amazonaws.com?

### ISSUE THREAD

**Issue by jsha** [dhs-ncats/pshtt#58]
amazonaws.com doesn't support HTTPS, but its HTTP version redirects eventually to https://aws.amazon.com. I believe this should be labeled as "Valid HTTPS" according to the rules in the README, but when I run pshtt I get "Valid HTTPS": false.

```
$ curl -IL http://amazonaws.com/
HTTP/1.1 301 Moved Permanently
Date: Mon, 13 Mar 2017 19:57:29 GMT
Server: Server
Location: http://aws.amazon.com
nnCoection: close
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 301 Moved Permanently
Date: Mon, 13 Mar 2017 19:57:29 GMT
Server: Server
Location: https://aws.amazon.com/
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Server: Server
Date: Mon, 13 Mar 2017 19:57:30 GMT
Content-Type: text/html;charset=UTF-8
Content-Length: 366144
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
x-amz-id-1: V93TTB078C28FJYNEV6Y
Last-Modified: Fri, 10 Mar 2017 20:07:16 GMT
Vary: Accept-Encoding,User-Agent
Set-Cookie: aws_lang=en; Domain=.amazon.com; Path=/
```

[
  {
    "Base Domain": "amazonaws.com",
    "Canonical URL": "http://amazonaws.com",
    "Defaults to HTTPS": false,
    "Domain": "amazonaws.com",
    "Domain Enforces HTTPS": null,
    "Domain Supports HTTPS": null,
    "Domain Uses Strong HSTS": false,
    "Downgrades HTTPS": false,
    "HSTS": false,
    "HSTS Entire Domain": null,
    "HSTS Header": null,
    "HSTS Max Age": null,
    "HSTS Preload Pending": false,
    "HSTS Preload Ready": false,
    "HSTS Preloaded": false,
    "HTTPS Bad Chain": null,
    "HTTPS Bad Hostname": null,
    "HTTPS Expired Cert": null,
    "Live": true,
    "Redirect": true,
    "Redirect To": "https://aws.amazon.com/",
    "Strictly Forces HTTPS": false,
    "Valid HTTPS": false,
    "endpoints": {
      "http": {
        "headers": {
          "Cneonction": "close",
          "Content-Length": "229",
          "Content-Type": "text/html; charset=iso-8859-1",
          "Date": "Mon, 13 Mar 2017 19:55:51 GMT",
          "Location": "http://aws.amazon.com",
          "Server": "Server"
        },
        "live": true,
        "redirect": true,
        "redirect_eventually_to": "https://aws.amazon.com/",
        "redirect_eventually_to_external": true,
        "redirect_eventually_to_http": false,
        "redirect_eventually_to_https": true,
        "redirect_eventually_to_subdomain": false,
        "redirect_immediately_to": "http://aws.amazon.com",
        "redirect_immediately_to_external": true,
        "redirect_immediately_to_http": true,
        "redirect_immediately_to_https": false,
        "redirect_immediately_to_subdomain": false,
        "redirect_immediately_to_www": null,
        "status": 301,
        "url": "http://amazonaws.com"
      },
      "https": {
        "headers": {},
        "hsts": false,
        "hsts_all_subdomains": null,
        "hsts_header": null,
        "hsts_max_age": null,
        "hsts_preload": null,
        "https_bad_chain": null,
        "https_bad_hostname": null,
        "https_expired_cert": null,
        "https_valid": null,
        "live": false,
        "redirect": null,
        "redirect_eventually_to": null,
        "redirect_eventually_to_external": null,
        "redirect_eventually_to_http": null,
        "redirect_eventually_to_https": null,
        "redirect_eventually_to_subdomain": null,
        "redirect_immediately_to": null,
        "redirect_immediately_to_external": null,
        "redirect_immediately_to_http": null,
        "redirect_immediately_to_https": null,
        "redirect_immediately_to_subdomain": null,
        "redirect_immediately_to_www": null,
        "status": null,
        "url": "https://amazonaws.com"
      },
      "httpswww": {
        "headers": {},
        "hsts": false,
        "hsts_all_subdomains": null,
        "hsts_header": null,
        "hsts_max_age": null,
        "hsts_preload": null,
        "https_bad_chain": null,
        "https_bad_hostname": null,
        "https_expired_cert": null,
        "https_valid": null,
        "live": false,
        "redirect": null,
        "redirect_eventually_to": null,
        "redirect_eventually_to_external": null,
        "redirect_eventually_to_http": null,
        "redirect_eventually_to_https": null,
        "redirect_eventually_to_subdomain": null,
        "redirect_immediately_to": null,
        "redirect_immediately_to_external": null,
        "redirect_immediately_to_http": null,
        "redirect_immediately_to_https": null,
        "redirect_immediately_to_subdomain": null,
        "redirect_immediately_to_www": null,
        "status": null,
        "url": "https://www.amazonaws.com"
      },
      "httpwww": {
        "headers": {
          "Cneonction": "close",
          "Content-Length": "229",
          "Content-Type": "text/html; charset=iso-8859-1",
          "Date": "Mon, 13 Mar 2017 19:55:52 GMT",
          "Location": "http://aws.amazon.com",
          "Server": "Server"
        },
        "live": true,
        "redirect": true,
        "redirect_eventually_to": "https://aws.amazon.com/",
        "redirect_eventually_to_external": true,
        "redirect_eventually_to_http": false,
        "redirect_eventually_to_https": true,
        "redirect_eventually_to_subdomain": false,
        "redirect_immediately_to": "http://aws.amazon.com",
        "redirect_immediately_to_external": true,
        "redirect_immediately_to_http": true,
        "redirect_immediately_to_https": false,
        "redirect_immediately_to_subdomain": false,
        "redirect_immediately_to_www": null,
        "status": 301,
        "url": "http://www.amazonaws.com"
      }
    }
  }
]

**Comment by konklone** [comment]
This is intended behavior, so perhaps we should make the README more clear. The README right now says:

>  A domain has "valid HTTPS" if it responds on port 443 at its canonical hostname with an unexpired valid certificate for the hostname.

The canonical hostname only refers to the canonical endpoint on the original domain. So if you're scanning `amazonaws.com`, the canonical hostname can only be `amazonaws.com` or `www.amazonaws.com`.

One of the goals of measuring `Valid HTTPS`, for an SLD or any of its subdomains, is to identify "is there anything preventing preloading?" As it stands, if `amazonaws.com` were preloaded, the redirect to `aws.amazon.com` would break and not function. So, I believe `Valid HTTPS` should be `false`.

**Comment by jsha** [comment]
Ah, yes, I was confused by:

> Canonical URL - A judgment call based on the observed redirect logic of the domain.

But now I see the difference between "URL" vs "hostname." Maybe just delete "at its canonical hostname" from the "Valid HTTPS" definition?

**Comment by konklone** [comment]
It's the other way around - `Canonical URL` is a judgment call based on the observed **internal** redirect logic of the domain. 

For `example.com`, the `Canonical URL` can have one of four values:

* http://example.com
* https://example.com
* http://www.example.com
* https://www.example.com

It can get slightly confusing when talking about canonical endpoints, because there are actually two calculations: which is the canonical hostname (`www` or the root), and what is the canonical protocol (`http:` or `https:`)? 

Sometimes only one of those aspects are relevant for a given calculation. For example, whether a domain has "Valid HTTPS" means looking at the validity (e.g. open on port 443, cert is valid for the hostname) of either `https://example.com` or `https://www.example.com`. So the code identifies the canonical hostname and then examines HTTPS at that hostname.

So it could be the case that "Valid HTTPS" is based on a scan of `https://www.example.com`, but that `http://www.example.com` is the "Canonical URL".

Is this making sense? It's definitely more complicated than I was originally imagining when I first wrote some of this logic, but it is designed for extreme resilience to arguments made by people undergoing compliance audits informed by this tool's criteria.

**Comment by jsha** [comment]
Looking at it again, I realize I was misunderstanding "Canonical URL." Intuitively I think the canonical URL for `amazonaws.com` is `https://aws.amazon.com`. But since Canonical URL can only encompass www/non-www varianets, that's not the Canonical URL and instead it's the domain itself. Maybe this:

> Canonical URL - A judgment call based on the observed redirect logic of the domain.
> Valid HTTPS - A domain has "valid HTTPS" if it responds on port 443 at its canonical hostname with an unexpired valid certificate for the hostname.

Should say:

> Canonical URL - One of the four endpoints described above; a judgment call based on the observed redirect logic of the domain.
> Valid HTTPS - A domain has "valid HTTPS" if it responds on port 443 at the hostname in its Canonical URL with an unexpired valid certificate for the hostname. This can be true even if the Canonical URL uses HTTP.

**Comment by konklone** [comment]
Those are good edits!

And I can understand why the definition might not feel intuitive. The best way I can frame the rationale is -

* Valid HTTPS - "If I preloaded the domain, would this break?"
* Canonical URL - "If I were to [hyperlink](https://pulse.cio.gov/https/domains/) `example.com`, what should the `href` attribute of the link be?"
