### ISSUE TITLE
Installation on Raspberry Pi 3... big headache

### ISSUE THREAD

**Issue by Kaplan89** [dhs-ncats/pshtt#73]
I'm trying to install pshtt on the Raspberry Pi 3, after numerous errors which I have fixed over time, I am only stuck with the following one. Building the wheel for **nassl** (necessary package for pshtt) simply does not succeed, _probably_ because **nassl** does not support ARM processors. 

Is there a way to replace **nassl** by something else during the **pshtt** installation?

The problem is mainly here actually:

**/tmp/pip-build-nngih_0d/nassl/bin/openssl/linux32/libssl.a: error adding symbols: File in wrong format
collect2: error**

Full log:

> Running setup.py install for nassl ... error
> Complete output from command /usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nngih_0d/nassl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i5j52ciu-record/install-record.txt --single-version-externally-managed --compile:
> running install
> running build
> running build_py
> creating build
> creating build/lib.linux-armv7l-3.5
> creating build/lib.linux-armv7l-3.5/nassl
> copying nassl/__init__.py -> build/lib.linux-armv7l-3.5/nassl
> copying nassl/ssl_client.py -> build/lib.linux-armv7l-3.5/nassl
> copying nassl/debug_ssl_client.py -> build/lib.linux-armv7l-3.5/nassl
> copying nassl/ocsp_response.py -> build/lib.linux-armv7l-3.5/nassl
> running build_ext
> building 'nassl._nassl' extension
> creating build/temp.linux-armv7l-3.5
> creating build/temp.linux-armv7l-3.5/nassl
> creating build/temp.linux-armv7l-3.5/nassl/_nassl
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/local/include/python3.5m -c nassl/_nassl/nassl.c -o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl.o -Wall
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/local/include/python3.5m -c nassl/_nassl/nassl_SSL_CTX.c -o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_SSL_CTX.o -Wall
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/local/include/python3.5m -c nassl/_nassl/nassl_SSL.c -o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_SSL.o -Wall
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/local/include/python3.5m -c nassl/_nassl/nassl_X509.c -o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_X509.o -Wall
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/local/include/python3.5m -c nassl/_nassl/nassl_errors.c -o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_errors.o -Wall
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/local/include/python3.5m -c nassl/_nassl/nassl_BIO.c -o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_BIO.o -Wall
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/local/include/python3.5m -c nassl/_nassl/nassl_X509_EXTENSION.c -o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_X509_EXTENSION.o -Wall
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/local/include/python3.5m -c nassl/_nassl/nassl_X509_NAME_ENTRY.c -o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_X509_NAME_ENTRY.o -Wall
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/local/include/python3.5m -c nassl/_nassl/nassl_SSL_SESSION.c -o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_SSL_SESSION.o -Wall
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/local/include/python3.5m -c nassl/_nassl/openssl_utils.c -o build/temp.linux-armv7l-3.5/nassl/_nassl/openssl_utils.o -Wall
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/local/include/python3.5m -c nassl/_nassl/nassl_OCSP_RESPONSE.c -o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_OCSP_RESPONSE.o -Wall
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/local/include/python3.5m -c nassl/_nassl/python_utils.c -o build/temp.linux-armv7l-3.5/nassl/_nassl/python_utils.o -Wall
> gcc -pthread -shared build/temp.linux-armv7l-3.5/nassl/_nassl/nassl.o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_SSL_CTX.o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_SSL.o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_X509.o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_errors.o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_BIO.o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_X509_EXTENSION.o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_X509_NAME_ENTRY.o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_SSL_SESSION.o build/temp.linux-armv7l-3.5/nassl/_nassl/openssl_utils.o build/temp.linux-armv7l-3.5/nassl/_nassl/nassl_OCSP_RESPONSE.o build/temp.linux-armv7l-3.5/nassl/_nassl/python_utils.o /tmp/pip-build-nngih_0d/nassl/bin/openssl/linux32/libssl.a /tmp/pip-build-nngih_0d/nassl/bin/openssl/linux32/libcrypto.a /tmp/pip-build-nngih_0d/nassl/bin/zlib/linux32/libz.a -o build/lib.linux-armv7l-3.5/nassl/_nassl.cpython-35m-arm-linux-gnueabihf.so
> /usr/bin/ld: /tmp/pip-build-nngih_0d/nassl/bin/openssl/linux32/libssl.a(s2_meth.o): Relocations in generic ELF (EM: 3)
> /usr/bin/ld: /tmp/pip-build-nngih_0d/nassl/bin/openssl/linux32/libssl.a(s2_meth.o): Relocations in generic ELF (EM: 3)
> /usr/bin/ld: /tmp/pip-build-nngih_0d/nassl/bin/openssl/linux32/libssl.a(s2_meth.o): Relocations in generic ELF (EM: 3)
> /tmp/pip-build-nngih_0d/nassl/bin/openssl/linux32/libssl.a: error adding symbols: File in wrong format
> collect2: error: ld returned 1 exit status
> error: command 'gcc' failed with exit status 1

**Comment by konklone** [comment]
So it looks like you're using Python 3, which the `master` branch here (and what's in `pip`) doesn't support. I'm working on Python 3 support here:

https://github.com/dhs-ncats/pshtt/compare/python3-support

Could you try that branch and let us know how it goes?

**Comment by konklone** [comment]
To be clear, there's still a bug on that branch preventing execution of `pshtt`. But, I'd like to see if installation of `pshtt` is successful.

**Comment by konklone** [comment]
To follow up - Python 3 support is now merged and working as of #74.

Is this still an issue on RPi?

**Comment by konklone** [comment]
Feel free to re-open if this is still a problem.
