### ISSUE TITLE
requirements.txt error

### ISSUE THREAD

**Issue by IanLee1521** [dhs-ncats/pshtt#87]
Relates to a comment I left on one of the recent pull requests, but the `requirements.txt` file actually has an error if you try to install it:

```
$ pip install -r requirements.txt
Invalid requirement: 'pyopenssl=17.2.0'
= is not a valid operator. Did you mean == ?
```

I would recommend changing it to simply ``pyopenssl`` without the pinned version.

/cc @konklone

**Comment by konklone** [comment]
Fixed by #90.
