### ISSUE TITLE
Add Python 3.6 classifier

### ISSUE THREAD

**Issue by IanLee1521** [dhs-ncats/pshtt#88]
I've been using / testing pshtt with Python 3.6 and haven't had any issues. We should update the setup.py classifier list at:

https://github.com/dhs-ncats/pshtt/blob/9ec891f0cbd4865d668309900d782b4030c4572c/setup.py#L50

**Comment by konklone** [comment]
Agreed, and confirmed that Python 3.6.1 works fine.

@h-m-f-t has been handling the PyPi-related work and changes, I'll defer to him for :+1: and implementation.
