### ISSUE TITLE
pyopenssl missing from setup.py

### ISSUE THREAD

**Issue by IanLee1521** [dhs-ncats/pshtt#94]
Hi all -- 

When the `requirements.txt` file was updated in #87 , it looks like `pyopenssl` didn't get added to the `setup.py` file (https://github.com/dhs-ncats/pshtt/blob/445d26b93f0d4e2679bb6da8a2832495869c57f7/setup.py#L58)

**Comment by h-m-f-t** [comment]
Thanks @IanLee1521!
