### ISSUE TITLE
Being nicer to hstspreload.org, chromium.googlesource.com, and publicsuffix.org

### ISSUE THREAD

**Issue by konklone** [dhs-ncats/pshtt#99]
The `pshtt` tool now hits 3 external endpoints per-scan: 

1. `hstspreload.org` for the Preload Pending status
2. `chromium.googlesource.com` for the Preloaded status
3. `publicsuffix.org` to incorporate Public Suffix checking into calculation of the "parent domain"

I've gotten reports from @lgarron that hstspreload.org is getting hit really hard by what are apparently large batches of `pshtt` runs. It's possible they're coming via [`domain-scan`](https://github.com/18f/domain-scan), and possible that they're not. And though I thought we did, we actually have no caching facility whatsoever for `hstspreload.org`. (Though if pshtt's internal batching is being used, it will only hit `hstspreload.org` once.)

So I think we definitely need to add caching for the `hstspreload.org` hit. 

I also wonder if it's best to incentivize downstream users of `pshtt` who are doing their own batching to take advantage of the caching features we have built in for (2) and (3), by requiring locations of cached files to be specified for those features to be enabled. 

But that would punish folks who are using pshtt's internal batching by adding additional complexity, since internal batching just holds the contents of the 3 requests in-memory the whole time as each domain is being processed.

Any ideas on ways we could help external batchers do the right thing, without making built-in batchers' lives harder?

**Comment by lgarron** [comment]
Would you feel comfortable using an `$XDG_CACHE` subfolder as a default (configurable) cache location, and providing only a flag to *disable* that cache?

**Comment by konklone** [comment]
Noting that I'd actually opened #84 and #85 a month ago to address some aspects of this, though neither talked about caching by default. Moving all the conversation here.

**Comment by IanLee1521** [comment]
One thought, discussed today on a call, is to modify those other tools (e.g. `domain-scan`) to use `pshtt` as a library, rather than as an external dependency. 

That should allow the same in-memory caching that `pshtt` does natively when running on multiple domains to be leveraged by `domain-scan`.
